version: '3'
services:
  cassandra:
    image: cassandra:3.11
    ports:
      - "9042:9042"
  statsd:
    image: graphiteapp/graphite-statsd
    ports:
      - "2003:2003"
      - "8125:8125"
      - "8126:8126"
  cadence:
    image: ubercadence/server:master-auto-setup
    ports:
     - "7933:7933"
     - "7934:7934"
     - "7935:7935"
     - "7939:7939"
    environment:
      - "CASSANDRA_SEEDS=cassandra"
      - "STATSD_ENDPOINT=statsd:8125"
      - "DYNAMIC_CONFIG_FILE_PATH=config/dynamicconfig/development.yaml"
    depends_on:
      - cassandra
      - statsd
  cadence-web:
    image: ubercadence/web:latest
    environment:
      - "CADENCE_TCHANNEL_PEERS=cadence:7933"
    ports:
      - "8088:8088"
    depends_on:
      - cadence

  servico-vendas:
    image: "servico-vendas"
    container_name: servico-vendas
    ports:
      - 8080:8080

  servico-pagamentos:
    image: "servico-pagamentos"
    container_name: servico-pagamentos
    ports:
      - 8081:8081

  servico-notificacoes:
    image: "servico-notificacoes"
    container_name: servico-notificacoes
    ports:
      - 8082:8082

  servico-logistica:
    image: "servico-logistica"
    container_name: servico-logistica
    ports:
      - 8083:8083

  servico-estoque:
    image: "servico-estoque"
    container_name: servico-estoque
    ports:
      - 8084:8084